
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        #gateway will be enabled to have the info of all the services registered in discovery service
        locator:
          enabled: true
          lower-case-service-id: true
      #all the routes of the services
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/cydeo/dev/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/cydeo/dev/project/**
          filters:
            - RewritePath=/project/(?<path>.*), /$\{path}
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/cydeo/dev/task/**
          filters:
            - RewritePath=/task/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  sleuth:
    sampler:
      #  1 means registering 100% of the logs in the docker running in port 9411
      probability: 1
  zipkin:
      base-url: http://host.docker.internal:9411
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.docker.internal:8080/auth/realms/master/protocol/openid-connect/certs

server:
  port: 8762

#Eureka server configuration
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator

info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'