spring:
  application:
    name: ticketing-project-rest
  profiles:
    active: default
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing-app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 9090

# eureka configuration
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      # eureka server runs in Docker not in localhost,
      # so we tell it to register all the services to this url
      defaultZone: http://discovery-service:8761/eureka/

#inforation about the health of each instances
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator

info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
    # '@ -- @' means it is getting information from maven
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'