spring:
  cloud:
    loadbalancer:
      ribbon:
        # do not want ribbon load balancer from Eureka server, instead wants to use from Docker
        enabled: false
server:
  #the Service discovery server will run on 8761 port
  port: 8761
#wants to use the service discovery run in the Eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
     #false means don't want registering to eureka server,
    register-with-eureka: false
    fetch-registry: false